n1 = input('Digite um numero: ')
n2 = input('Digite outro numero: ')
res = int(n1) + int(n2)
#print('A soma entre:', n1 , ' e ' , n2 ,'=' , res)
print('A soma entre: {} e {} vale {}' .format(n1, n2, res))
